# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(db_column='aid', primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, db_column='abalance', null=True, verbose_name='account balance')),
                ('filler', models.CharField(blank=True, max_length=84, null=True, verbose_name='filler')),
            ],
            options={
                'managed': False,
                'db_table': 'pgbench_accounts',
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.IntegerField(db_column='bid', primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, db_column='bbalance', null=True, verbose_name='balance')),
                ('filler', models.CharField(blank=True, max_length=88, null=True, verbose_name='filler')),
            ],
            options={
                'managed': False,
                'db_table': 'pgbench_branches',
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(db_column='hid', primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(blank=True, null=True, verbose_name='difference')),
                ('mtime', models.DateTimeField(blank=True, null=True, verbose_name='modification time')),
                ('filler', models.CharField(blank=True, max_length=22, null=True, verbose_name='filler')),
            ],
            options={
                'managed': False,
                'db_table': 'pgbench_history',
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.IntegerField(db_column='tid', primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(blank=True, db_column='tbalance', null=True, verbose_name='teller balance')),
                ('filler', models.CharField(blank=True, max_length=84, null=True, verbose_name='filler')),
            ],
            options={
                'managed': False,
                'db_table': 'pgbench_tellers',
                'verbose_name': 'teller',
                'verbose_name_plural': 'tellers',
            },
        ),
    ]
